name: 问题：使用遇到问题（报错、样式与示例不一致等）
description: 此模板适用于解决使用博客生成器遇到的问题。
title: "【问题】："
labels: help
body:
  - type: markdown
    attributes:
      value: | 
        请务必认真填写，足够的信息能帮助我们快速定位问题并及时修复。
  - type: checkboxes
    id: checks
    attributes:
      label: 检查清单
      description: 请认真检查以下清单中的每一项，并在相符的项前打勾。
      options:
        - label: 已经搜索过，没有发现类似 issue。
        - label: 已经搜索过[博客生成器使用文档](https://previwe-blog-builder.haloged.eu.org/doc/)，没有发现相关内容。
  - type: dropdown
    id: theme-version
    attributes:
      label: 博客生成器版本
      description: 请选择您所使用的官网版本。
      options:
        - 0.x.x
        - Other
    validations:
      required: true
  - type: input
    id: bug-url
    attributes:
      label: 复现地址
      description: 请输入可供复现的访问地址。
      placeholder: "如: https://haloged-studio.eu.org/index/admin/editor?id=1"
    validations:
      required: true
  - type: textarea
    id: description
    attributes:
      label: 问题描述
      description: 请告诉我们发生了什么？
      placeholder:  请详细描述您所遇到的情况：复现步骤、操作过程、注册方式、用户名、截图等内容。
    validations:
      required: true